# Generated by Django 6.0.2 on 2026-02-26 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image_paths',
            field=models.TextField(null=True),
        ),
    ]
