# Generated by Django 6.0.2 on 2026-03-01 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_menuitem_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image_paths',
            field=models.TextField(blank=True, null=True),
        ),
    ]
